<a href="https://colab.research.google.com/github/pavanreddy0829/Hosting/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Arrays ( array.shape, len(array), array.ndim, array.dtype, array.astype(type),
type(array))


In [ ]:
import numpy as np

Shape of an Array
The shape of an array is the number of elements in each dimension.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
x = np.array([1, 2, 3, 4])
print(x.shape)

(4,)


In [ ]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array.shape)

(3, 3)


len(array)

In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9])
print(array.size)

9


In [ ]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array.size)

9


In [ ]:

l=[1,2,3,4]
arr=np.array(l)
print("Array isn",arr)
print("And dimension is",arr.ndim)

l=[[1,2,3],[3,2,1],[1,0,1]]
arr=np.array(l)
print("nArray isn",arr)
print("And dimension is",arr.ndim)

l=[[[1,2],[2,1]],[[3,4],[4,3]]]
arr=np.array(l)
print("nArray isn",arr)
print("And dimension is",arr.ndim)

Array isn [1 2 3 4]
And dimension is 1
nArray isn [[1 2 3]
 [3 2 1]
 [1 0 1]]
And dimension is 2
nArray isn [[[1 2]
  [2 1]]

 [[3 4]
  [4 3]]]
And dimension is 3


### dtype

In [ ]:
print(np.dtype(np.int16))

print("\n")

print(np.dtype([('f1', np.int16)]))

print("\n")

print(np.dtype([('f1', [('f1', np.int16)])]))
print("\n")

print(np.dtype([('f1', np.uint), ('f2', np.int32)]))

print("\n")

print(np.dtype([('a','f8'),('b','S10')]))

print("\n")

print(np.dtype("i4, (2,3)f8"))

print("\n")

print(np.dtype([('hello',(int,3)),('world',np.void,10)]))
print("\n")

print(np.dtype((np.int16, {'x':(np.int8,0), 'y':(np.int8,1)})))

print("\n")

print(np.dtype({'names':['gender','age'], 'formats':['S1',np.uint8]}))

print("\n")

print(np.dtype({'surname':('S25',0),'age':(np.uint8,25)}))

int16


[('f1', '<i2')]


[('f1', [('f1', '<i2')])]


[('f1', '<u8'), ('f2', '<i4')]


[('a', '<f8'), ('b', 'S10')]


[('f0', '<i4'), ('f1', '<f8', (2, 3))]


[('hello', '<i8', (3,)), ('world', 'V10')]


(numpy.int16, [('x', 'i1'), ('y', 'i1')])


[('gender', 'S1'), ('age', 'u1')]


[('surname', 'S25'), ('age', 'u1')]


### ASTYPE and TYPE

In [ ]:
x = np.array([1, 2, 2.5])
print(x)
print(x.astype(int))

[1.  2.  2.5]
[1 2 2]


# ARRAY MANIPULATION

### append
"""
This function adds values at the end of an input array. The append operation is not inplace, a new array is allocated. Also the dimensions of the input arrays must match otherwise ValueError will be generated.

The function takes the following parameters.

numpy.append(arr, values, axis)"""

In [ ]:
a = np.array([[1,2,3],[4,5,6]]) 

print('First array:' )
print(a) 
print('\n'  )

print('Append elements to array:') 
print(np.append(a, [7,8,9]))
print('\n')  

print('Append elements along axis 0:') 
print(np.append(a, [[7,8,9]],axis = 0)) 
print('\n')  

print('Append elements along axis 1:')
print(np.append(a, [[5,5,5],[7,8,9]],axis = 1))

First array:
[[1 2 3]
 [4 5 6]]


Append elements to array:
[1 2 3 4 5 6 7 8 9]


Append elements along axis 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Append elements along axis 1:
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


### insert
This function inserts values in the input array along the given axis and before the given index. If the type of values is converted to be inserted, it is different from the input array. Insertion is not done in place and the function returns a new array. Also, if the axis is not mentioned, the input array is flattened.

The insert() function takes the following parameters −

numpy.insert(arr, obj, values, axis)

In [ ]:
a = np.array([[1,2],[3,4],[5,6]]) 

print('First array:') 
print(a) 
print('\n')  

print('Axis parameter not passed. The input array is flattened before insertion.')
print(np.insert(a,3,[11,12]) )
print('\n')
print('Axis parameter passed. The values array is broadcast to match input array.')

print('Broadcast along axis 0:') 
print(np.insert(a,1,[11],axis = 0))
print('\n')

print('Broadcast along axis 1:')
print(np.insert(a,1,11,axis = 1))


First array:
[[1 2]
 [3 4]
 [5 6]]


Axis parameter not passed. The input array is flattened before insertion.
[ 1  2  3 11 12  4  5  6]


Axis parameter passed. The values array is broadcast to match input array.
Broadcast along axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


Broadcast along axis 1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


### RESIZE
This function returns a new array with the specified size. If the new size is greater than the original, the repeated copies of entries in the original are contained. The function takes the following parameters.

numpy.resize(arr, shape)

In [ ]:
a = np.array([[1,2,3],[4,5,6]]) 

print('First array:') 
print(a)
print('\n')

print('The shape of first array:') 
print(a.shape) 
print('\n')  
b = np.resize(a, (3,2)) 

print('Second array:') 
print(b) 
print('\n')  

print('The shape of second array:')
print(b.shape) 
print('\n')  
# Observe that first row of a is repeated in b since size is bigger 

print('Resize the second array:')
b = np.resize(a,(3,3)) 
print(b)

First array:
[[1 2 3]
 [4 5 6]]


The shape of first array:
(2, 3)


Second array:
[[1 2]
 [3 4]
 [5 6]]


The shape of second array:
(3, 2)


Resize the second array:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


### DELETE
This function returns a new array with the specified subarray deleted from the input array. As in case of insert() function, if the axis parameter is not used, the input array is flattened. The function takes the following parameters −

Numpy.delete(arr, obj, axis)

In [ ]:
a = np.arange(12).reshape(3,4) 

print('First array:') 
print(a) 
print('\n')  

print('Array flattened before delete operation as axis not used:')
print(np.delete(a,5))
print('\n') 

print('Column 2 deleted:')  
print(np.delete(a,1,axis = 1))
print('\n')  

print('A slice containing alternate values from array deleted:') 
a = np.array([1,2,3,4,5,6,7,8,9,10]) 
print(np.delete(a, np.s_[::2]))

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array flattened before delete operation as axis not used:
[ 0  1  2  3  4  6  7  8  9 10 11]


Column 2 deleted:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


A slice containing alternate values from array deleted:
[ 2  4  6  8 10]


### CONCATENATE

Concatenation refers to joining. This function is used to join two or more arrays of the same shape along a specified axis. The function takes the following parameters.

numpy.concatenate((a1, a2, ...), axis)

In [ ]:
a = np.array([[1,2],[3,4]]) 

print('First array:') 
print(a)
print('\n')  
b = np.array([[5,6],[7,8]]) 

print('Second array:') 
print(b)
print('\n')
# both the arrays are of same dimensions 

print('Joining the two arrays along axis 0:')
print(np.concatenate((a,b))) 
print('\n')  

print('Joining the two arrays along axis 1:')
print(np.concatenate((a,b),axis = 1))

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


### HSTACK
Variants of numpy.stack function to stack so as to make a single array horizontally.

In [ ]:
import numpy as np 
a = np.array([[1,2],[3,4]]) 

print('First array:') 
print(a) 
print('\n')  
b = np.array([[5,6],[7,8]]) 

print('Second array:')
print(b)
print('\n')

print('Horizontal stacking:') 
c = np.hstack((a,b)) 
print(c )


First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]


### VSTACK
Variants of numpy.stack function to stack so as to make a single array vertically.

In [ ]:
a = np.array([[1,2],[3,4]]) 

print('First array:') 
print(a) 
print('\n')  
b = np.array([[5,6],[7,8]]) 

print('Second array:') 
print(b) 
print('\n')

print('Vertical stacking:' )
c = np.vstack((a,b)) 
print(c)

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Vertical stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# MATHEMATICAL OPERATIONS

In [ ]:
a = np.array([0,30,45,60,90]) 

print('Sine of different angles:' )
# Convert to radians by multiplying with pi/180 
print(np.sin(a*np.pi/180))
print('\n')  

print('Cosine values for angles in array:')
print(np.cos(a*np.pi/180)) 
print('\n')  

print('Tangent values for given angles:') 
print(np.tan(a*np.pi/180)) 

Sine of different angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [ ]:
print(np.dot(3, 4))
print('\n')

print(np.dot([2j, 3j], [2j, 3j]))
print('\n')

a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
print(np.dot(a, b))



12


(-13+0j)


[[4 1]
 [2 2]]


In [ ]:
#numpy.roots(p)[source]
#Return the roots of a polynomial with coefficients given in p.

coeff = [3.2, 2, 1]
print(np.roots(coeff))

[-0.3125+0.46351241j -0.3125-0.46351241j]


In [ ]:
#np.sqrt
arr1 = np.sqrt([1, 4, 9, 16])
arr2 = np.sqrt([6, 10, 18])
  
print("square-root of an array1  : ", arr1)
print("square-root of an array2  : ", arr2)

square-root of an array1  :  [1. 2. 3. 4.]
square-root of an array2  :  [2.44948974 3.16227766 4.24264069]


In [ ]:
#np.log
in_array = [1, 3, 5, 2**8]
print ("Input array : ", in_array)
  
out_array = np.log(in_array)
print ("Output array : ", out_array)
  
  
print("\nnp.log(4**4) : ", np.log(4**4))
print("np.log(2**8) : ", np.log(2**8))

Input array :  [1, 3, 5, 256]
Output array :  [0.         1.09861229 1.60943791 5.54517744]

np.log(4**4) :  5.545177444479562
np.log(2**8) :  5.545177444479562


In [ ]:
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print('First array:') 
print(a)
print( '\n')  

print('Second array:') 
b = np.array([10,10,10]) 
print(b) 
print('\n')  

print('Add the two arrays:')
print(np.add(a,b)) 
print('\n')  

print('Subtract the two arrays:')
print(np.subtract(a,b)) 
print('\n')  

print('Multiply the two arrays:')
print(np.multiply(a,b)) 
print('\n')  

print('Divide the two arrays:') 
print(np.divide(a,b))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[10 10 10]


Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [ ]:
#mean
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:') 
print(a)
print('\n')  

print('Applying mean() function:') 
print(np.mean(a) )
print('\n' )

print('Applying mean() function along axis 0:') 
print(np.mean(a, axis = 0))
print('\n')  

print('Applying mean() function along axis 1:') 
print(np.mean(a, axis = 1))

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


Applying mean() function:
3.6666666666666665


Applying mean() function along axis 0:
[2.66666667 3.66666667 4.66666667]


Applying mean() function along axis 1:
[2. 4. 5.]


In [ ]:
#medain
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:') 
print(a)
print('\n')  

print('Applying median() function:') 
print(np.median(a) )
print('\n' )

print('Applying median() function along axis 0:') 
print(np.median(a, axis = 0))
print('\n')  

print('Applying median() function along axis 1:') 
print(np.median(a, axis = 1))

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


Applying median() function:
4.0


Applying median() function along axis 0:
[3. 4. 5.]


Applying median() function along axis 1:
[2. 4. 5.]


In [ ]:
"""
Standard Deviation
Standard deviation is the square root of the average of squared deviations from mean. The formula for standard deviation is as follows −

std = sqrt(mean(abs(x - x.mean())**2))
"""

In [ ]:
print(np.std([1,2,3,4]))

1.118033988749895



## numpy.corrcoef
numpy.corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>, *, dtype=None)[source]
Return Pearson product-moment correlation coefficients.

Please refer to the documentation for cov for more detail. The relationship between the correlation coefficient matrix, R, and the covariance matrix, C, is

The values of R are between -1 and 1, inclusive.

In [ ]:
rng = np.random.default_rng(seed=42)
xarr = rng.random((3, 3))
print(xarr)
print('\n')
print("after applying corrcoef")
R1 = np.corrcoef(xarr)
print(R1)

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]


after applying corrcoef
[[ 1.          0.99256089 -0.68080986]
 [ 0.99256089  1.         -0.76492172]
 [-0.68080986 -0.76492172  1.        ]]


In [ ]:
yarr = rng.random((3, 3))
print(yarr)
print('\n')

R2 = np.corrcoef(xarr, yarr)
print(R2)

[[0.45038594 0.37079802 0.92676499]
 [0.64386512 0.82276161 0.4434142 ]
 [0.22723872 0.55458479 0.06381726]]


[[ 1.          0.99256089 -0.68080986  0.75008178 -0.934284   -0.99004057]
 [ 0.99256089  1.         -0.76492172  0.82502011 -0.97074098 -0.99981569]
 [-0.68080986 -0.76492172  1.         -0.99507202  0.89721355  0.77714685]
 [ 0.75008178  0.82502011 -0.99507202  1.         -0.93657855 -0.83571711]
 [-0.934284   -0.97074098  0.89721355 -0.93657855  1.          0.97517215]
 [-0.99004057 -0.99981569  0.77714685 -0.83571711  0.97517215  1.        ]]
