<a href="https://colab.research.google.com/github/pavanreddy0829/Hosting/blob/main/Task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1.Import the numpy package under the name np and Print the numpy version and the configuration 

In [3]:
import numpy as np
np.version

<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>

### 2.Create a null vector of size 10

In [4]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 3.Create Simple 1-D array and check type and check data types in array

In [5]:
a = np.array([1,2,3,4])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


### 4.How to find number of dimensions, bytes per element and bytes of memory used?

In [6]:
# create a numpy 1d-array
x = np.array([100,20,34])

#to find number of dimensions
print(x.ndim)
print("Size of the array: ",
      x.size)
  
print("Memory size of one array element in bytes: ",
      x.itemsize)
  
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",
      x.size * x.itemsize)

1
Size of the array:  3
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 24


### 5.Create a null vector of size 10 but the fifth value which is 1

In [8]:
a = np.zeros((10))
print(a)
a[4]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 6.Create a vector with values ranging from 10 to 49

In [9]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 7.Reverse a vector (first element becomes last)

In [13]:
a = np.arange(10,21)
print(a[::-1])

[20 19 18 17 16 15 14 13 12 11 10]


### 8.Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
a= np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 9.Find indices of non-zero elements from [1,2,0,0,4,0]

In [18]:
a = np.array([1,2,0,0,4])
ar =a.nonzero()
print(ar)

(array([0, 1, 4]),)


### 10.Create a 3x3 identity matrix


In [20]:
a = np.identity(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 11.Create a 3x3x3 array with random values

In [23]:
a =np.arange(0,27).reshape(3,3,3)
print(a)
print(a.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
3


### 12.Create a 10x10 array with random values and find the minimum and maximum values

In [24]:
a = np.random.randint(100,size=(10,10))
print(a)

[[43 17 56  7 31 30 94 99 86 54]
 [ 5 55 55 24 65 24 35 34 27 70]
 [43 38 17 87 95 31 86 70 32 29]
 [87 35 82 50 83 32 27 25 29 73]
 [ 2 30 67 79 97 53 42 81 99 75]
 [49 58 47 53 72 27 98 83 82 31]
 [ 1 33 69  6 11 23 96 60 66 63]
 [24 73 73 25  9 23  8 49  2  7]
 [97 35 14 65 53 60 94 73 47 44]
 [57 76 25 35 81 66  1  1 29 31]]


In [25]:
#min
print(a.min())

#max
print(a.max())

1
99


### 13.Create a random vector of size 30 and find the mean value


In [27]:
a = np.random.randint(300,size=30)
print(a)

[211 149 136 263  86 277 130 103 294 147   8  53 256 242  25 176 276 196
 193  98 144  36 189 137 135 149 201 243  15  90]


In [28]:
#mean
print(a.mean())

155.26666666666668


### 14.Create a 2d array with 1 on the border and 0 inside

In [30]:
x = np.ones((5,5),dtype=int)
print("Original array:")
print(x)

Original array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [31]:
x[1:-1,1:-1]=0
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### 15.How to add a border (filled with 0's) around an existing array? 

In [36]:
#using pad attribute
a = np.ones((5,5),dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [37]:
print(a.shape)
a = np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(a)
print(a.shape)

(5, 5)
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]
(7, 7)


### How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13
get first row only
get 3rd column only
get [2, 4, 6]
replace 13 by 20

In [40]:
a = np.array([[ 1 ,2 ,3, 4, 5, 6 ,7],[ 8, 9, 10, 11, 12, 13, 14]])
print(a)
print(a.ndim)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
2


In [42]:
a[1,5]

13

In [46]:
print(a[0])

[1 2 3 4 5 6 7]


In [48]:
print(a[:,2])

[ 3 10]


In [50]:
print(a[:-1,1::2])

[[2 4 6]]


In [51]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


### 17.How to Convert a 1D array to a 2D array with 2 rows

In [52]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Convert 1D array to a 2D numpy array of 2 rows and 3 columns
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### 18.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`
Desired Output:

### array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [61]:
a = np.array([1,2,3])
print("output")
a=np.r_[np.repeat(a,3),np.tile(a,3)]
print(a)

output
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


### 19.Write a program to show how Numpy taking less memory compared to Python List?



In [59]:
import sys
print("memory usage in list")
l = range(1000)
print(l)
print(sys.getsizeof(l[0]))
print(sys.getsizeof(l))
print("memory usage in numpy")
a = np.arange(1000)
print(a.size)
print(a.itemsize)
print(a.size*a.itemsize)

memory usage in list
range(0, 1000)
24
48
memory usage in numpy
1000
8
8000


### 20.Write a program to show how Numpy taking less time compared to Python List?

In [56]:
import time
print('in list')
l=range(1000000)
l1=range(1000000)
start = time.time()
result = [(x+y) for x,y in zip(l,l1)]
print((time.time()-start)*1000)

in list
129.9753189086914


In [57]:
print('in numpy')
n1 = np.arange(1000000)
n2 = np.arange(1000000)
start=time.time()
result1=n1+n2
print((time.time()-start)*1000)

in numpy
4.190683364868164
